site_name: curso_fpga
repo_url: https://github.com/cirofabianbermudez/curso_fpga
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: teal
      accent: orange
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    
      primary: teal
      accent: orange
  font:
    text: Roboto

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cirofabianbermudez
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CiroBermudez
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ciro-fabian-bermudez-marquez-a93096227/
  analytics:
    provider: google
    property: G-9K60RTS6RK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 <a href="https://github.com/cirofabianbermudez"  target="_blank" rel="noopener">Ciro Bermudez</a>
